lint:
  actions_nf_test: false
  files_unchanged:
    - .gitignore
    - assets/nf-core-riboseq_logo_light.png
    - docs/images/nf-core-riboseq_logo_dark.png
    - docs/images/nf-core-riboseq_logo_light.png
  merge_markers:
    - modules/nf-core/bowtie2/align/tests/main.nf.test.snap
  nextflow_config:
    - config_defaults:
        - params.ribo_database_manifest
  nf_test_content: false
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Jonathan Manning
  description: Analysis of ribosome profiling, or Ribo-seq (also named ribosome footprinting)
  force: false
  is_nfcore: true
  name: riboseq
  org: nf-core
  outdir: .
  version: 1.3.0dev
