channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::bioconductor-deseq2=1.42.0
  - bioconda::bioconductor-apeglm=1.24.0
  - bioconda::bioconductor-complexheatmap=2.18.0
  - conda-forge::r-data.table=1.15.0
  - conda-forge::r-dplyr=1.1.4
  - conda-forge::r-readr=2.1.5
  - conda-forge::r-purrr=1.0.2
  - conda-forge::r-tibble=3.2.1
  - conda-forge::r-ggplot2=3.4.4
  - conda-forge::r-ggrepel=0.9.4
