// Count Ribo-seq p-sites which are in-frame.
// P-site counts are passed as bedGraph files (forward & reverse), e.g.,
// as generated by plastid make_wiggle. The counts are summed over all
// in-frame positions of CDS segments in a GTF file.

process QUANTIFY_INFRAME_PSITE_PLASTID {
    tag "$gtf"
    label 'process_single'

    conda "bioconda::bedtools=2.31.1"
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/bedtools==2.31.1--h13024bc_3' :
        'biocontainers/bedtools:2.31.1--h13024bc_3' }"

    input:
    tuple val(id), path(forward_bedgraph), path(reverse_bedgraph)
    tuple val(meta), path(gtf)
    val feature

    output:
    tuple val(meta), path("*_inframe_psite_counts.tsv"), emit: counts
    path "versions.yml", emit: versions

    script:
    """
    # get p-sites from CDS segments in GTF file
    awk -F'\\t' -v OFS='\\t' '
        \$3 == "CDS" && \$9 ~ /${feature}_id "/ {

            # parse GTF file
            chrom = \$1; start = \$4; end = \$5; strand = \$7; phase = \$8
            feature = \$9; sub(/.*${feature}_id "/, "", feature); sub(/".*/, "", feature)

            # print coordinates of codon starts
            frame = strand == "+" ? phase : (3 - phase + end - start) % 3
            for (pos = start + frame; pos <= end; pos += 3)
                   print chrom, pos-1, pos, feature, 0, strand
        }
    ' "$gtf" |
    sort -u > psites.bed

    # collate sample IDs and bedgraph files
    echo -e '${ [id, forward_bedgraph, reverse_bedgraph].transpose().collect { it.join('\\t') }.join('\\n') }' |

    while IFS=\$'\\t' read SAMPLE FORWARD_BEDGRAPH REVERSE_BEDGRAPH; do

        # append strand to bedgraph files and merge forward/reverse bedgraph files into a single stream
        (
            sed 's/\$/\\t0\\t+/' "\$FORWARD_BEDGRAPH"
            sed 's/\$/\\t0\\t-/' "\$REVERSE_BEDGRAPH"
        ) |

        # aggregate in-frame p-site counts by gene/transcript
        bedtools intersect -wa -wb -loj -a psites.bed -b /dev/stdin -s |
        awk -F'\\t' -v OFS='\\t' -v SAMPLE="\$SAMPLE" '{ print SAMPLE, \$4, int(\$10) }' |
        bedtools groupby -g 1,2 -c 3 -o sum

    done > "${feature}_inframe_psite_counts.tsv"

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        bedtools: \$(bedtools --version | cut -f2 -dv)
        awk: \$(awk 2>&1 | head -n1 | cut -f2 -d' ' | cut -f2 -dv)
    END_VERSIONS
    """
}
