// Count Ribo-seq p-sites which are in-frame.
// P-site counts are passed as bedGraph files (forward & reverse), e.g.,
// as generated by plastid make_wiggle. The counts are summed over all
// positions of an in-frame p-sites BED file.

process QUANTIFY_INFRAME_PSITE_PLASTID {
    tag "$meta.id"
    label 'process_single'

    conda "bioconda::bedtools=2.31.1"
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/bedtools==2.31.1--h13024bc_3' :
        'biocontainers/bedtools:2.31.1--h13024bc_3' }"

    input:
    tuple val(meta), path(forward_bedgraph), path(reverse_bedgraph)
    tuple val(meta2), path(inframe_psites)

    output:
    tuple val(meta), path("*_inframe_psite_counts.tsv"), emit: counts
    path "versions.yml", emit: versions

    script:
    """
    # append strand to bedgraph files and merge forward/reverse bedgraph files into a single stream
    (
        sed 's/\$/\\t0\\t+/' "$forward_bedgraph"
        sed 's/\$/\\t0\\t-/' "$reverse_bedgraph"
    ) |

    # aggregate in-frame p-site counts by gene/transcript
    bedtools intersect -wa -wb -a $inframe_psites -b /dev/stdin -s |
    sort -k4,4 |
    bedtools groupby -g 4 -c 10 -o sum |
    sed 's/^/${meta.id}\\t/' \\
    > "${meta.id}.${meta2.feature}_inframe_psite_counts.tsv"

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        bedtools: \$(bedtools --version | cut -f2 -dv)
    END_VERSIONS
    """

    stub:
    """
    touch ${meta.id}.${meta2.feature}_inframe_psite_counts.tsv

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        bedtools: \$(bedtools --version | cut -f2 -dv)
    END_VERSIONS
    """
}
