// Quantify Ribo-seq p-sites which are in-frame.
// P-site counts are passed as bedGraph files (forward & reverse), e.g.,
// as generated by plastid make_wiggle. The counts are averaged over the
// total number of p-sites in the gene/transcript. Then, the count matrix
// given as input is modified: all counts of Ribo-seq samples in the matrix
// are replaced by the counts computed by this module.

process QUANTIFY_INFRAME_PSITE {
    tag "$meta.id, $gtf"
    label 'process_single'

    conda "bioconda::bedtools=2.31.1"
    container "${ workflow.containerEngine == 'singularity' && !task.ext.singularity_pull_docker_container ?
        'https://depot.galaxyproject.org/singularity/bedtools==2.31.1--h13024bc_3' :
        'biocontainers/bedtools:2.31.1--h13024bc_3' }"

    input:
    tuple val(id), path(forward_bedgraph), path(reverse_bedgraph)
    tuple val(meta), path(counts)
    tuple val(meta2), path(gtf)
    val feature

    output:
    tuple val(meta), path("*_counts_length_scaled.tsv"), emit: counts_length_scaled
    path "versions.yml", emit: versions

    script:
    """
    # get p-sites from CDS segments in GTF file
    awk -F'\\t' -v OFS='\\t' '
        \$3 == "CDS" && \$9 ~ /${feature}_id "/ {

            # parse GTF file
            chrom = \$1; start = \$4; end = \$5; strand = \$7; phase = \$8
            feature = \$9; sub(/.*${feature}_id "/, "", feature); sub(/".*/, "", feature)

            # print coordinates of codon starts
            frame = strand == "+" ? phase : (3 - phase + end - start) % 3
            for (pos = start + frame; pos <= end; pos += 3)
                   print chrom, pos-1, pos, feature, 0, strand
        }
    ' "$gtf" |
    sort -u > psites.bed

    # collate sample IDs and bedgraph files
    echo -e '${ [id, forward_bedgraph, reverse_bedgraph].transpose().collect { it.join('\\t') }.join('\\n') }' |

    while IFS=\$'\\t' read SAMPLE FORWARD_BEDGRAPH REVERSE_BEDGRAPH; do

        # append strand to bedgraph files and merge forward/reverse bedgraph files into a single stream
        (
            sed 's/\$/\\t0\\t+/' "\$FORWARD_BEDGRAPH"
            sed 's/\$/\\t0\\t-/' "\$REVERSE_BEDGRAPH"
        ) |

        # aggregate in-frame p-site counts by gene/transcript
        bedtools intersect -wa -wb -loj -a psites.bed -b /dev/stdin -s |
        awk -F'\\t' -v OFS='\\t' -v SAMPLE="\$SAMPLE" '{ print SAMPLE, \$4, int(\$10) }' |
        bedtools groupby -g 1,2 -c 3 -o sum

    done |

    # in the count matrix, replace Salmon's Ribo-seq counts with the counts computed above
    awk -F'\\t' -v OFS='\\t' '

        # receive the new counts from stdin
        FILENAME == "/dev/stdin" {
            # cache sample names and counts
            samples[\$1]
            count[\$1, \$2] = \$3
        }

        # the old count matrix comes after stdin
        FILENAME != "/dev/stdin" {
            if (FNR == 1) {
                # the column headers tell us the sample names
                for (i = 3; i <= NF; i++)
                    header[i] = \$i
            } else {
                # replace values whenever we find a column of a Ribo-seq sample
                for (i = 3; i <= NF; i++)
                    if (header[i] in samples)
                        \$i = count[header[i], \$1] + 0
            }
            print
        }
    ' /dev/stdin ${counts} > "${feature}_counts_length_scaled.tsv"

    cat <<-END_VERSIONS > versions.yml
    "${task.process}":
        bedtools: \$(bedtools --version | cut -f2 -dv)
        awk: \$(awk 2>&1 | head -n1 | cut -f2 -d' ' | cut -f2 -dv)
    END_VERSIONS
    """
}
